sonar.projectKey=year2-se1
sonar.projectName=Year2_SE1
sonar.projectVersion=sprint6
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend/src
sonar.tests=backend/tests,frontend/src

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=**/.venv/**,**/venv/**,**/node_modules/**,**/htmlcov/**,**/coverage/**,**/__pycache__/**,**/*.min.js
sonar.test.inclusions=backend/tests/**/*.py,frontend/src/**/*.test.jsx